# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name=b'Section headers')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Creation date')),
                ('comment', models.TextField(verbose_name=b'Comment')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to=b'uploads/', verbose_name=b'Attached file')),
                ('up_votes', models.IntegerField(default=0, verbose_name=b'Upvotes')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name=b'Section name')),
                ('comment', models.CharField(max_length=64, verbose_name=b'Section comment')),
                ('over_all_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_simple_forum.MainSection')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name=b'Thread name')),
                ('views', models.BigIntegerField(default=0, verbose_name=b'Amount of views')),
                ('disabled', models.BooleanField(default=False, verbose_name=b'Disabled')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Creation date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_simple_forum.Section')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_simple_forum.Thread'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
    ]
