# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_forum', '0002_auto_20170830_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='created_date',
        ),
    ]
